{{- if and .Values.istio.enabled }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: productpage
  namespace: {{ .Release.Namespace }} 
spec:
  hosts:
  - example.com
  gateways: 
  - bookinfo-gateway
  http:
  - route:
    - destination:
        host: productpage
        port:
          number: 9080
{{- if .Values.istio.fault.enabled }}
    fault:
      abort:
        httpStatus: {{ .Values.istio.fault.httpStatus }} 
        percentage:
          value: {{ .Values.istio.fault.percentage }}
{{- end }}
{{- end }}